apiVersion: skaffold/v1alpha5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - context: src
      image: gcr.io/sanche-testing-project/kubecode/bookshelf
  local:
    push: true
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/**
profiles:
- name: local
  build:
    local:
      useDockerCLI: true
      useBuildkit: false
- name: staging
  build:
    googleCloudBuild:
      projectId: sanche-testing-project