apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: java-guestbook-backend
  labels:
    app: java-guestbook
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: java-guestbook
        tier: backend
    spec:
      containers:
      - name: backend
        image: java-guestbook-backend
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_DB_ADDR
          value: "java-guestbook-mongodb:27017"
    initContainers:
        - name: mongo-init
          image: busybox:1.28
          command: ['sh', '-c', 'echo $(date) "> checking for envt var for mongo-service"; until nslookup mongo-service; do echo $(date) "> waiting for mongo"; sleep 2; done; echo $(date) "> got envt var for mongo-service"']
          