apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bookshelf-frontend
  labels:
    app: bookshelf
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bookshelf
        tier: frontend
    spec:
      containers:
      - name: bookshelf-app
        image: bookshelf
        imagePullPolicy: Always
        env:
        - name: PROCESSES
          value: bookshelf
        - name: PROJECT_ID
          value: sanche-testing-project
        - name: DEBUG_PORT
          value: '3000'
        - name: SERVER_PORT
          value: '8080'
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        - name: MONGO_URI
          value: 'mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@mongo-service:27017/admin'
        ports:
        - name: http-server
          containerPort: 8080