apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshelf-frontend
  labels:
    app: bookshelf
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshelf
      tier: frontend
  template:
    metadata:
      labels:
        app: bookshelf
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: bookshelf
        imagePullPolicy: Always
        env:
        - name: PROCESSES
          value: bookshelf
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: gcp-project-config
              key: project-id
        - name: DEBUG_PORT
          value: "3000"
        - name: PORT
          value: "8080"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        - name: MONGO_HOST
          value: "mongo-service"
        ports:
        - name: http-server
          containerPort: 8080