apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookshel
    tier: db
  name: mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: bookshelf
    tier: db