apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshelf-worker
  labels:
    app: bookshelf
    tier: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshelf
      tier: worker
  template:
    metadata:
      labels:
        app: bookshelf
        tier: worker
    spec:
      containers:
      - name: worker
        image: bookshelf
        imagePullPolicy: Always
        env:
        - name: PROCESSES
          value: worker
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: gcp-project-config
              key: project-id
        - name: DEBUG_PORT
          value: "3000"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        - name: MONGO_HOST
          value: "mongo-service"