apiVersion: skaffold/v1alpha5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - context: .
      image: hello-world
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/**
profiles:
  - name: no-push # do not push the images, only build
    build:
      local:
        push: false
