apiVersion: skaffold/v1alpha5
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
    - context: src
      image: gcr.io/sanche-testing-project/kubecode/hello-world
  local:
    push: true
    useDockerCLI: true
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/**
profiles:
# use the local profile to build images locally using the Docker CLI
- name: local
  build:
    local:
      useDockerCLI: true
      useBuildkit: false
# use the staging profile to build images in the cloud using Google Cloud Build
- name: staging
  build:
    googleCloudBuild:
      projectId: sanche-testing-project