apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: gcr.io/sanche-testing-project/kubecode/hello-world
        env:
        - name: DEBUG_PORT
          value: '3000'
        - name: SERVER_PORT
          value: '8080'
        ports:
        - containerPort: 8080         