# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: java-hello-world"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-hello-world
  template:
    metadata:
      labels:
        app: java-hello-world
    spec:
      containers:
        - name: server
          image: java-hello-world
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"


