apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: guestbook-backend
      context: src/backend
    - image: guestbook-frontend
      context: src/frontend
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: false
    useDockerCLI: false
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/**
profiles:
  - build:
      googleCloudBuild:
        projectId: YOUR_PROJECT_ID
    deploy: {}
    name: cloudbuild
